### ISSUE TITLE
Missing new graduates in  data.json

### ISSUE THREAD

**Issue by WWanda** [j2kun/math-genealogy-visualizer#9]
Ph.D.s who graduated in May 2017 are not in your data set. However, they are present at https://genealogy.math.ndsu.nodak.edu

Could you please update the data?

Many thanks!
WWanda

**Comment by j2kun** [comment]
Just updated the data.

However, note that I won't be doing this regularly, because I don't have access to the underlying database maintained by `ndsu`. Therefore, I have to scrape their site for the updates manually, and I'm not planning to set up a server that does this on a schedule. If you want updated data in the future, you can clone this repository and the data scraping repository, and fetch the data yourself.

https://github.com/j2kun/math-genealogy-scraper

**Comment by Markvy** [comment]
Is Perelman (the famous one) in the the data set?

**Comment by j2kun** [comment]
Yes, but his name is listed "Grigorii Yakovlevich Perelman" so without the precise spelling it's hard to find him among the many other Grigory's, Grigori's, Gregory's, and Perlman's, Perelman's, and Perleman's in the database.
